# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            ğŸ‘¨â€ğŸš€ Voyager28 
tagline:          'Through Space & Time!'
description:      "Galactic Pilgrim"

url:              http://

author:
  name:           'ğŸ‘¨â€ğŸš€ voyager28'
  url:            https://github.com/agentbigman

paginate:         5

collections:
    rails-devops:
        output: true
        permalink: /:collection/:path/
    blog:
        output: true
        permalink: /:collection/:path/
    bytes:
        output: true
        permalink: /:collection/:path/

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/agentbigman/agentbigman.github.io

# Gems
gems:
  - jekyll-redirect-from
